[package]
name = "libkeylogger"
version = "0.1.1"
authors = ["Zhan Poplavskyi <gan.popl@gmail.com>"]
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "winuser"] }
