[package]
name = "libkeylogger"
version = "0.2.3"
authors = ["Zhan Poplavskyi <gan.popl@gmail.com>"]
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["windef", "minwindef", "winuser"] }

[dev-dependencies]
enigo = "0.1.3"
